### ISSUE TITLE
mvdir typescript version

### ISSUE THREAD

**Issue by wangjue666** [m-ahmadi/mvdir#4]
hi~ @m-ahmadi 

The mvdir package has been very helpful for my project, But now most projects are written in typescript. so I implement its [TS version](https://github.com/sellerartifact/mvdir-ts).  It was created by [modernjs](https://modernjs.dev/en/index.html).

I am very grateful for your contribution and sharing in the community.

Sincere thanks!

**Comment by m-ahmadi** [comment]
Hello and thank you for the kind words.
I looked at the [TS version](https://github.com/sellerartifact/mvdir-ts).
There are some things I should mention.

The `TS version` has added the following things:

----- |----
------|-----
prettier       | which is not "really" needed
pnpm lock file | which I don't know why, and cannot go figure that out right now.
husky          | for git hooks which just runs `lint-staged`
lint-staged    | for linting which again is not "really" needed
eslint         | which is probably because `modern-js` uses it somewhere
nvm config     | again something that's not needed here
rimraf         | which is probably a dependecy of another thing
vscode dir     | which contains vscode configs, and I don't why it should be in the repo
changeset dir  | which again I don't know its purpose (and can't spend time figuring that our out right now)

I understand that some of these are items needed by `modern-js` to do its work.

What I mean by "something is not really needed", is not that it's a bad thing,
it's just that it does not provide enough value relative to its cost to justify
using it in this case/repo. (it could very well fit in another situation)
I understand these are `devDependecies` and "not real", but I'm looking at it
from the viewpoint of what's been added relative to what purpose does it serve.

So after all of that, I then look at the code in `src/index.tx` and it's just
the same code in javascript, except with `esm` style module imports. The only
thing of real value added here is the type definition files. One in
`src/help.ts` which I think is used internally by `modern-js` and the real one
is generated in `types/index.d.ts`, I paste its code in the following:
```js
declare class CustomError {
    code: number;
    message: string;
    constructor(code: number, m1: string, m2?: string);
}
interface Options {
    overwrite?: boolean;
    copy?: boolean;
    log?: boolean;
}

declare function mvdir(_src?: string, _dest?: string, _opts?: Options): Promise<CustomError | undefined>;

export { mvdir as default };
```
So basically If you add a type definition file to the `mvdir` repo, it
essentially becomes the same thing as the `mvdir-ts`. The concept I meantioned
earlier about "cost/value added" does not really fit here I think.

At some point in the past, I remember thinking about adding a typescript
`type-definition` file, but then I don't why I didn't, but even now when I
think about it, it seems unnecessary. The reason is because this
repo only contains:
- 1 function with 3 arguments, 2 of which are strings, 1 is an `options` object with 3 boolean props
- 1 error object with a `code` and `message` props, (which return 4 kinds of erros, codes 1,2,3,4)

So as you can see there is not much here that needs type information.
It's already simple enough, but I guess the benefit of that `type-definition`
file is that, when someone is using this function, they can see a nice little
summary of those arguments and the different errors returned and so on.

**Comment by m-ahmadi** [comment]
Another benefit of manually adding a `type-definition` file is you can provide a little documentation-like description.

For example, taking the auto-generated `.d.ts` file from before and adding complementary things to it.
Like the `ErrorCode` enum or the little description for the function.

```ts
declare class CustomError {
	code: ErrorCode ;
	message: string;
	constructor(code: number, m1: string, m2?: string);
}
enum ErrorCode {
	InvalidArgs = 1,
	SrcNotExists = 2,
	DestAlreadyExists = 3,
	DestIsExistingFile = 4,
}

interface Options {
	overwrite?: boolean;
	copy?: boolean;
	log?: boolean;
}

/**
	Move files or whole directories from a srouce path to a destination path.  
	By default does not overwrite, but can if `{overwrite: true}` is set in the `Options` argument.  
	Returns `undefined` if operation is successfull or an `CustomError` object.  
	`CustomError` can have codes `1`, `2`, `3`, or `4` described as follows:
	1. Invalid argument(s).
	2. No such file or directory: ...
	3. Destination already exists: ...
	4. Destination is an existing file: ...
*/
declare function mvdir(_src?: string, _dest?: string, _opts?: Options): Promise<CustomError | undefined>;


export { mvdir as default };

```

Which looks like below upon using the module:
![image](https://github.com/m-ahmadi/mvdir/assets/16363767/a9bb9444-f877-411e-9207-452d56f94532)

**Comment by wangjue666** [comment]
hi @m-ahmadi 

Thank you for taking the time to review the TypeScript version of mvdir and for sharing your valuable feedback. I appreciate your thorough analysis of the additions I made to the project.
﻿
I understand your concerns regarding the inclusion of certain tools and files in the TypeScript version. You rightly pointed out that tools like `prettier, pnpm lock file, lint-staged,` etc., are standard in modern frontend development workflows. My intention behind including these tools was to align with industry best practices and ensure code consistency and maintainability.
﻿
However, I also acknowledge your perspective that in the context of this specific project, some of these additions may not provide significant value relative to their cost. Upon reflection, I realize that prioritizing simplicity and clarity in the codebase is crucial.
﻿
Regarding the type definition files, I agree with your assessment that the simplicity of the original JavaScript code might not necessitate extensive type annotations. Your suggestion to focus on providing clear documentation and concise type definitions resonates with me.
﻿
Once again, I appreciate your constructive criticism and willingness to engage in this discussion.
﻿
Best regards.

**Comment by m-ahmadi** [comment]
Thank you again for your kind words🙏. I appreciate your understanding.

I made a PR for adding the type-definition file.

I also added a little more information to the function description.

You're welcome to suggest anything in the #5 thread.
